FROM mizucopo/stockvalue-exporter:latest

COPY .python-version \
     pyproject.toml \
     uv.lock \
     README.md \
     /app/

COPY src/ /app/src/

RUN apk add --no-cache --virtual .build-deps \
      gcc \
      linux-headers \
      musl-dev \
      python3-dev \
    && uv sync --locked \
    && apk del .build-deps
