services:
  prod:
    build:
      context: ./docker/
      dockerfile: Dockerfile.prod
    image: mizucopo/stockvalue-exporter:latest
    platform: linux/amd64
  dev:
    build:
      context: ./docker/
      dockerfile: Dockerfile.dev
    image: mizucopo/stockvalue-exporter:develop
    platform: linux/amd64
