services:
  prod:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    image: mizucopo/stockvalue-exporter:latest
    platform: linux/amd64
  dev:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    image: mizucopo/stockvalue-exporter:develop
    platform: linux/amd64
