# ビルドステージ
FROM python:3.13.4-alpine AS builder

RUN apk add --no-cache \
    tzdata \
  && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && echo "Asia/Tokyo" > /etc/timezone


# 実行ステージ
FROM python:3.13.4-alpine

COPY --from=builder /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
COPY --from=builder /etc/timezone /etc/timezone

ENV PIP_ROOT_USER_ACTION=ignore

WORKDIR /app

RUN pip install uv==0.7.12

# docker run --rm -it -v $(pwd)/app:/app mizucopo/stockvalue-exporter:latest /bin/sh
